-- Tabelas para MySQL
-- Copie e execute no phpMyAdmin do 000webhost

CREATE TABLE IF NOT EXISTS os_master (
    CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    DATA_INICIO VARCHAR(10),
    HORA_INICIO VARCHAR(8),
    PREVISAO_ENTREGA VARCHAR(10),
    DATA_TERMINO VARCHAR(10),
    HORA_TERMINO VARCHAR(8),
    DATA_ENTREGA VARCHAR(10),
    HORA_ENTREGA VARCHAR(8),
    FK_ATENDENDE INT,
    PROBLEMA TEXT,
    OBSERVACOES TEXT,
    FK_EMPRESA INT,
    FK_USUARIO INT,
    DOCUMENTO VARCHAR(20),
    NOME VARCHAR(100),
    FONE1 VARCHAR(20),
    FONE2 VARCHAR(20),
    SITUACAO VARCHAR(2),
    NUMERO_SERIE VARCHAR(50),
    DESCRICAO VARCHAR(100),
    MODELO VARCHAR(50),
    MARCA VARCHAR(50),
    COR VARCHAR(30),
    IMEI VARCHAR(20),
    PLACA VARCHAR(10),
    KM DECIMAL(10,2),
    SUBTOTAL_PECAS DECIMAL(10,2),
    TOTAL_SERVICOS DECIMAL(10,4),
    TOTAL_GERAL DECIMAL(10,4),
    ENDERECO VARCHAR(150),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    UF VARCHAR(2),
    NUMERO VARCHAR(10),
    TIPO_SERVICO VARCHAR(50),
    FK_CLIENTE INT,
    LAUDO_TECNICO_VISUAL TEXT,
    JUSTIFICATIVA TEXT,
    ARRANHADO VARCHAR(1),
    TRINCADO VARCHAR(1),
    REPRODUZ VARCHAR(1),
    CARREGANDO VARCHAR(1),
    PELICULA VARCHAR(1),
    CHIP VARCHAR(1),
    BATERIA VARCHAR(1),
    CARTAO VARCHAR(1),
    CAIXA VARCHAR(1),
    MARCAS_USO VARCHAR(1),
    MANCHA_TELA VARCHAR(1),
    PARAFUSOS_EXT VARCHAR(1),
    CAMERA_TRINCADA VARCHAR(1),
    TOUCH_FUNCIONANDO VARCHAR(1),
    DISPLAY_SEM_AVARIAS VARCHAR(1),
    VIDRO_DANIFICADO VARCHAR(1),
    BOTAO_HOME_FUNCIONANDO VARCHAR(1),
    TOUCH_ID VARCHAR(1),
    FACE_ID VARCHAR(1),
    GRAVA_AUDIO VARCHAR(1),
    LEITURA_CHIP VARCHAR(1),
    TESTE_WIFI VARCHAR(1),
    BLUETOOTH_FUNCIONA VARCHAR(1),
    FONE_AURICULAR VARCHAR(1),
    CHAVINHA_VIBRA VARCHAR(1),
    TESTE_CAMERA_TRASEIRA VARCHAR(1),
    TESTE_CAMERA_FRONTAL VARCHAR(1),
    SENSOR_PROXIMIDADE VARCHAR(1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS os_detalhe (
    CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    FK_OS_MASTER INT,
    FK_FUNCIONARIO INT,
    FK_PRODUTO INT,
    DATA_INICIO VARCHAR(10),
    HORA_INICIO VARCHAR(8),
    DATA_TERMINO VARCHAR(10),
    HORA_TERMINO VARCHAR(8),
    DISCRIMINACAO VARCHAR(200),
    QTD DECIMAL(10,3),
    PRECO DECIMAL(10,4),
    TOTAL DECIMAL(10,4),
    FK_USUARIO INT,
    FK_EMPRESA INT,
    TIPO VARCHAR(1),
    SITUACAO VARCHAR(20),
    FOREIGN KEY (FK_OS_MASTER) REFERENCES os_master(CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS os_avaria (
    CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    FK_OS_MASTER INT,
    TIPO_AVARIA VARCHAR(50),
    POSICAO_X INT,
    POSICAO_Y INT,
    OBSERVACAO TEXT,
    FOREIGN KEY (FK_OS_MASTER) REFERENCES os_master(CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS os_imagem (
    CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    FK_OS_MASTER INT,
    ITEM INT,
    FOTO LONGBLOB,
    FOREIGN KEY (FK_OS_MASTER) REFERENCES os_master(CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS produto (
    CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(200)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS usuarios (
    CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    LOGIN VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
